# Generated by Django 6.0.6 on 2026-06-23 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issuer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('tax_id', models.CharField(max_length=50, verbose_name='Tax ID')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('tax_id', models.CharField(max_length=50, verbose_name='Tax ID')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=100)),
                ('account_currency', models.CharField(max_length=10)),
                ('bank_name', models.CharField(max_length=255)),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='procurement.issuer')),
            ],
            options={
                'verbose_name_plural': 'Bank accounts',
                'ordering': ['bank_name'],
            },
        ),
        migrations.CreateModel(
            name='PO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=50, unique=True, verbose_name='PO Number')),
                ('contract_number', models.CharField(blank=True, max_length=100)),
                ('issued_at', models.DateField(verbose_name='Issue Date')),
                ('requested_delivery_date', models.DateField(blank=True, null=True)),
                ('warranty', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='procurement.issuer')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='procurement.supplier')),
            ],
            options={
                'verbose_name': 'Purchase Order',
                'verbose_name_plural': 'Purchase Orders',
                'ordering': ['-issued_at', '-po_number'],
            },
        ),
        migrations.CreateModel(
            name='POItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commercial_model_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_price_currency', models.CharField(default='USD', max_length=10)),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement.po')),
            ],
            options={
                'verbose_name': 'PO Item',
                'verbose_name_plural': 'PO Items',
            },
        ),
        migrations.CreateModel(
            name='POPaymentTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('percentage_due', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='% Due')),
                ('expected_date', models.DateField()),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_terms', to='procurement.po')),
            ],
            options={
                'verbose_name': 'PO Payment Term',
                'verbose_name_plural': 'PO Payment Terms',
                'ordering': ['expected_date'],
            },
        ),
        migrations.CreateModel(
            name='SupplierBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=100)),
                ('account_currency', models.CharField(max_length=10)),
                ('bank_name', models.CharField(max_length=255)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='procurement.supplier')),
            ],
            options={
                'verbose_name_plural': 'Supplier bank accounts',
                'ordering': ['bank_name'],
            },
        ),
    ]
