# Generated by Django 6.0.6 on 2026-06-23 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuer',
            name='email',
        ),
        migrations.CreateModel(
            name='IssuerEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='procurement.issuer')),
            ],
            options={
                'verbose_name_plural': 'Issuer emails',
                'ordering': ['email'],
            },
        ),
    ]
