# Generated by Django 6.0.6 on 2026-06-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_remove_issuer_email_issueremail'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierbankaccount',
            name='account_address',
            field=models.TextField(blank=True),
        ),
    ]
