# Generated by Django 6.0.6 on 2026-06-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_supplierbankaccount_account_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuer',
            name='tax_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Tax ID'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='tax_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Tax ID'),
        ),
    ]
