# Generated by Django 6.0.6 on 2026-06-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0004_alter_issuer_tax_id_alter_supplier_tax_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='po',
            name='requested_delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Lead Time Requested'),
        ),
    ]
