# Generated by Django 5.2.15 on 2026-06-24 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0005_alter_po_requested_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='po',
            name='incoterms',
            field=models.CharField(blank=True, choices=[('EXW', 'EXW – Ex Works'), ('FCA', 'FCA – Free Carrier'), ('CPT', 'CPT – Carriage Paid To'), ('CIP', 'CIP – Carriage and Insurance Paid To'), ('DAP', 'DAP – Delivered at Place'), ('DPU', 'DPU – Delivered at Place Unloaded'), ('DDP', 'DDP – Delivered Duty Paid'), ('FAS', 'FAS – Free Alongside Ship'), ('FOB', 'FOB – Free on Board'), ('CFR', 'CFR – Cost and Freight'), ('CIF', 'CIF – Cost Insurance and Freight')], max_length=3, verbose_name='Incoterms'),
        ),
        migrations.AddField(
            model_name='po',
            name='port',
            field=models.CharField(blank=True, max_length=255, verbose_name='Port'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='issuer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='issueremail',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='po',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='poitem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='popaymentterm',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='supplierbankaccount',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
