# Generated by Django 5.2.15 on 2026-06-24 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0006_po_incoterms_po_port_alter_bankaccount_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalRepresentative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Phone/Celular')),
                ('issuers', models.ManyToManyField(blank=True, related_name='legal_representatives', to='procurement.issuer')),
            ],
            options={
                'verbose_name': 'Legal Representative',
                'verbose_name_plural': 'Legal Representatives',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='po',
            name='signer_primary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='primary_pos', to='procurement.legalrepresentative', verbose_name='Primary Signer'),
        ),
        migrations.AddField(
            model_name='po',
            name='signer_secondary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_pos', to='procurement.legalrepresentative', verbose_name='Secondary Signer'),
        ),
        migrations.CreateModel(
            name='POGeneratedPDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=100)),
                ('pdf_data', models.BinaryField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_pdfs', to='procurement.po')),
            ],
            options={
                'verbose_name': 'Generated PDF',
                'verbose_name_plural': 'Generated PDFs',
                'ordering': ['-generated_at'],
            },
        ),
    ]
