# Generated by Django 5.2.15 on 2026-06-25 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0009_pogeneratedpdf_is_signed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'ordering': ['beneficiary_bank_name'], 'verbose_name_plural': 'Bank accounts'},
        ),
        migrations.AlterModelOptions(
            name='supplierbankaccount',
            options={'ordering': ['beneficiary_bank_name'], 'verbose_name_plural': 'Supplier bank accounts'},
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='account_currency',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='supplierbankaccount',
            name='account_address',
        ),
        migrations.RemoveField(
            model_name='supplierbankaccount',
            name='account_currency',
        ),
        migrations.RemoveField(
            model_name='supplierbankaccount',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='supplierbankaccount',
            name='bank_name',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='beneficiary_bank_account_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='beneficiary_bank_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='beneficiary_bank_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='beneficiary_bank_swift_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='beneficiary_customer_account',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='beneficiary_customer_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='beneficiary_customer_branch',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='beneficiary_customer_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='intermediate_bank_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='intermediate_bank_fed_aba',
            field=models.CharField(blank=True, max_length=50, verbose_name='Intermediate Bank FED/ABA'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='intermediate_bank_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='intermediate_bank_swift_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='supplierbankaccount',
            name='beneficiary_bank_account_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='supplierbankaccount',
            name='beneficiary_bank_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='supplierbankaccount',
            name='beneficiary_bank_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='supplierbankaccount',
            name='beneficiary_bank_swift_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='supplierbankaccount',
            name='beneficiary_customer_account',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='supplierbankaccount',
            name='beneficiary_customer_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='supplierbankaccount',
            name='beneficiary_customer_branch',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='supplierbankaccount',
            name='beneficiary_customer_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='supplierbankaccount',
            name='intermediate_bank_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='supplierbankaccount',
            name='intermediate_bank_fed_aba',
            field=models.CharField(blank=True, max_length=50, verbose_name='Intermediate Bank FED/ABA'),
        ),
        migrations.AddField(
            model_name='supplierbankaccount',
            name='intermediate_bank_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='supplierbankaccount',
            name='intermediate_bank_swift_address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
