# Generated by Django 5.2.15 on 2026-06-25 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0010_update_bank_account_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='beneficiary_bank_iban',
            field=models.CharField(blank=True, max_length=50, verbose_name='Beneficiary Bank IBAN'),
        ),
        migrations.AddField(
            model_name='supplierbankaccount',
            name='beneficiary_bank_iban',
            field=models.CharField(blank=True, max_length=50, verbose_name='Beneficiary Bank IBAN'),
        ),
    ]
