# Generated by Django 5.2.15 on 2026-06-25 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0012_add_po_prefix_suffix_to_issuer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Code')),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['code'],
            },
        ),
    ]
