# Generated by Django 5.2.15 on 2026-06-25 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0013_add_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuer',
            name='po_prefix',
            field=models.CharField(choices=[('IDS', 'IDS'), ('EBM', 'EBM'), ('IDSSE', 'IDSSE')], max_length=10, verbose_name='PO Prefix'),
        ),
        migrations.AlterField(
            model_name='issuer',
            name='po_suffix',
            field=models.CharField(choices=[('PA', 'PA'), ('HK', 'HK'), ('PE', 'PE'), ('CL', 'CL'), ('MX', 'MX'), ('BR', 'BR'), ('AR', 'AR'), ('US', 'US')], max_length=10, verbose_name='PO Suffix'),
        ),
    ]
