# Generated by Django 5.2.15 on 2026-07-28 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0016_product_financial_category_po_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='po',
            name='sienge_cost_center_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sienge Cost Center ID'),
        ),
        migrations.AddField(
            model_name='po',
            name='sienge_department_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sienge Department ID'),
        ),
    ]
