# Generated by Django 5.2.15 on 2026-09-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0020_rename_supplier_to_counterparty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterparty',
            name='sienge_creditor_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sienge Creditor ID'),
        ),
        migrations.AlterField(
            model_name='issuer',
            name='po_suffix',
            field=models.CharField(choices=[('PA', 'PA'), ('HK', 'HK'), ('PE', 'PE'), ('CL', 'CL'), ('CO', 'CO'), ('MX', 'MX'), ('BR', 'BR'), ('AR', 'AR'), ('US', 'US')], max_length=10, verbose_name='PO Suffix'),
        ),
        migrations.AlterField(
            model_name='po',
            name='po_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='PO/Invoice Number'),
        ),
    ]
