# Generated by Django 5.2.15 on 2026-09-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0021_add_co_suffix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='po',
            name='incoterms',
            field=models.CharField(blank=True, choices=[('N/A', 'N/A – Not Applicable (Services)'), ('EXW', 'EXW – Ex Works'), ('FCA', 'FCA – Free Carrier'), ('CPT', 'CPT – Carriage Paid To'), ('CIP', 'CIP – Carriage and Insurance Paid To'), ('DAP', 'DAP – Delivered at Place'), ('DPU', 'DPU – Delivered at Place Unloaded'), ('DDP', 'DDP – Delivered Duty Paid'), ('FAS', 'FAS – Free Alongside Ship'), ('FOB', 'FOB – Free on Board'), ('CFR', 'CFR – Cost and Freight'), ('CIF', 'CIF – Cost Insurance and Freight')], max_length=3, verbose_name='Incoterms'),
        ),
    ]
