# Generated by Django 5.2.15 on 2026-09-09 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0022_add_na_incoterm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='po',
            name='document_type',
        ),
    ]
